server:
  port: 8080

es:
  id: ${ES_ID}
  password: ${ES_PASSWORD}
  endpoint: ${ES_ENDPOINT}

springdoc:
  version: 1.0.0
  swagger-ui:
    # path: /swagger-ui.html
    disable-swagger-default-url: false
    config-url: /v3/api-docs/swagger-config
    url: /v3/api-docs

spring:
  output:
    ansi:
      enabled: always

logging:
#  file:
#    name: ${LOG_PATH} # slf4j를 사용할 때 생기는 로그 파일 경로
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace